# Generated by Django 3.2.12 on 2025-04-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sched_App', '0005_auto_20250410_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
