# Generated by Django 3.2 on 2025-05-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sched_App', '0008_auto_20250501_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
